[package]
name = "geo-songs"
version = "0.1.1"
edition = "2021"

[dependencies]
glob = "0.3.1"
reqwest = { version = "0.11.23", features = ["multipart"] }
rocket = "0.5.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.29"
