name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo test --all-features

    formatting:
        name: cargo fmt
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions-rust-lang/setup-rust-toolchain@v1
            with:
              components: rustfmt
          - name: Rustfmt Check
            uses: actions-rust-lang/rustfmt@v1

    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin]

        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo build --release --target ${{ matrix.target }}