name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo test --all-features

    build:
        runs-on: ubuntu-latest
        needs: test

        outputs:
            version: ${{ steps.get-version.outputs.version }}

        strategy:
            matrix:
                target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin]

        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - id: get-version
              run: echo "version=$(cat Cargo.toml | grep version | head -n 1 | cut -d \" -f 2)" >> $GITHUB_OUTPUT
            - run: rustup target add ${{ matrix.target }}
            - run: cargo build --release --target ${{ matrix.target }}
            - uses: actions/upload-artifact@v4
              with:
                  name: "${{ matrix.target }}-${{ steps.get-version.outputs.version }}"
                  path: target/${{ matrix.target }}/release/geo-songs