name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo test --all-features

    build:
        runs-on: ${{ matrix.target }}
        needs: test

        outputs:
            version: ${{ steps.get-version.outputs.version }}

        strategy:
            matrix:
                target: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - id: get-version
              run: echo "version=$(cat Cargo.toml | grep version | head -n 1 | cut -d \" -f 2)" >> $GITHUB_OUTPUT
            - run: cargo build --release
            - uses: actions/upload-artifact@v4
              with:
                  name: "${{ matrix.target }}-${{ steps.get-version.outputs.version }}"
                  path: target/release/geo-song
